imagen_proactiva_generate_form:
    resource: "@ImagenProactivaGenerateFormBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@ImagenProactivaGenerateFormBundle/Controller/"
    type:     annotation
