ImagenProactiva\GenerateFormBundle\Entity\Form:
    type: entity
    table: null
    repositoryClass: ImagenProactiva\GenerateFormBundle\Entity\FormRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            type: string
            length: 255

    oneToMany:
        resps:
            targetEntity: Response
            mappedBy: forms
            cascade: ["remove"]            
    
    lifecycleCallbacks: {  }
