ImagenProactiva\GenerateFormBundle\Entity\Question:
    type: entity
    table: null
    repositoryClass: ImagenProactiva\GenerateFormBundle\Entity\QuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            type: string
            length: 255

    oneToMany:
        answers:
            targetEntity: Answer
            mappedBy: question
            cascade: ["remove"]            
    
    lifecycleCallbacks: {  }
