imagen_proactiva_generate_form_index:
    path:     /form/index
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:index }
    
imagen_proactiva_generate_checkbox:
    path:     /form/checkbox
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:checkbox }
    
imagen_proactiva_generate_radio:
    path:     /form/radio
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:radio }
    
imagen_proactiva_generate_text:
    path:     /form/text
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:text }
    
imagen_proactiva_generate_create_checkbox:
    path:     /form/create
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:recibir }
