imagen_proactiva_index:
    path:     /index
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:index }
    
imagen_proactiva_generate_checkbox:
    path:     /checkbox
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:checkbox }
    
imagen_proactiva_generate_radio:
    path:     /radio
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:radio }
    
imagen_proactiva_generate_text:
    path:     /text
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:text }
    
imagen_proactiva_generate_create:
    path:     /create
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:createQuestion }

imagen_proactiva_generate_view_questions:
    path:     /view/questions
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:viewallquestions }
    
imagen_proactiva_view_question:
    path:     /question/view/{id}
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:viewQuestion } 