imagen_proactiva_index:
    path:     /index
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:index }
    
imagen_proactiva_generate_checkbox:
    path:     /checkbox
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:checkbox }
    
imagen_proactiva_generate_radio:
    path:     /radio
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:radio }
    
imagen_proactiva_generate_text:
    path:     /text
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:text }
    
imagen_proactiva_generate_create:
    path:     /create
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:createQuestion }

imagen_proactiva__view_all_questions:
    path:     /question/all
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:viewAllquestions }
    
imagen_proactiva_view_question:
    path:     /question/view/{id}
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:viewQuestion }
    
imagen_proactiva_delete_question:
    path:     /question/delete/{id}
    defaults: { _controller: ImagenProactivaGenerateFormBundle:GenerateForm:deleteQuestion }